# Generated by Django 3.2.5 on 2021-08-19 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_data_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
