# Generated by Django 3.2.5 on 2021-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_html', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default='none', upload_to='videos/'),
        ),
    ]
